name: Release

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Luacheck
        uses: nebularg/actions-luacheck@86af42dcf465915896671903fcdec3e01a492e87
        with:
          args: --no-color -o 011

  release:
    runs-on: ubuntu-latest
    needs: build
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Retail
        uses: BigWigsMods/packager@ff497ddc591e87719d9da67f6dc106a4aa6a873d

      - name: Burning Crusade
        uses: BigWigsMods/packager@ff497ddc591e87719d9da67f6dc106a4aa6a873d
        with:
          args: -g bcc